# Generated by Django 5.0 on 2024-01-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_order_total_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('date', models.CharField(max_length=5)),
                ('cvv', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
